import { logError, logInfo, resolveAttachments, timingSafeEqual, withNotes } from "@looped/core";
import type {
  AgentEvent,
  Attachment,
  MediaLimits,
  ResolvedMedia,
  RunResult,
  Trigger,
} from "@looped/core";
import { NO_REPLY } from "./text.ts";

// The pushed email transport (Plan 7, phase 1): an inbound-mail provider
// (Resend) receives mail for a domain, parses the MIME and POSTs a signed
// webhook here. The webhook carries metadata only, so the trigger fetches the
// body from the provider's API before waking the agent, and delivers the
// agent's reply back through the same API as an ordinary email send.
//
// An email address is an open channel — anyone on the internet can write to
// it — so the sender allowlist is required and every request's signature is
// verified before the payload is even parsed.

const RESEND_API = "https://api.resend.com";

/** The metadata carried by Resend's `email.received` webhook (bodies come from the API). */
export interface ResendInboundData {
  email_id: string;
  from: string;
  to?: string[];
  subject?: string;
  message_id?: string;
}

/**
 * A received email, normalized. This is the shape Resend's
 * GET /emails/receiving/{id} returns, and the pulled transports map their
 * messages into it so rendering and threading are shared.
 */
export interface ReceivedEmail {
  from: string;
  to?: string[];
  reply_to?: string[] | null;
  subject?: string;
  created_at?: string;
  text?: string | null;
  html?: string | null;
  headers?: Record<string, string>;
  message_id?: string;
  /**
   * Attachments that can produce their bytes. Every transport knows where its
   * bytes live — inline in the MIME, or one fetch away on an API it already
   * talks to — so a mail attachment resolves like any other channel's.
   */
  attachments?: Attachment[];
}

/** One attachment as Resend's receiving API describes it. */
interface ResendAttachment {
  filename?: string;
  content_type?: string;
  size?: number;
  /** Base64 of the file, when Resend parsed and kept it. */
  content?: string;
}

/** Base64 (not URL-safe) to bytes. */
function base64Bytes(data: string): Uint8Array {
  return Uint8Array.from(atob(data.replace(/\s+/g, "")), (c) => c.charCodeAt(0));
}

/**
 * Map Resend's receiving-email JSON into {@linkcode ReceivedEmail}.
 *
 * Resend's inbound payload carries each attachment's bytes as base64 in
 * `content`. It does not always: a message Resend declined to parse in full
 * arrives as metadata with no `content` and no url to go get it, and there is
 * no second endpoint that serves the file. Such an attachment can only be
 * described, so its fetch says why rather than inventing bytes.
 */
export function resendToReceived(body: Record<string, unknown>): ReceivedEmail {
  const raw = (body.attachments ?? []) as ResendAttachment[];
  return {
    ...(body as unknown as ReceivedEmail),
    attachments: raw.map((a) => ({
      filename: a.filename,
      mediaType: a.content_type,
      size: a.size,
      fetch: () =>
        a.content
          ? Promise.resolve(base64Bytes(a.content))
          : Promise.reject(new Error("Resend delivered no content for this attachment")),
    })),
  };
}

/** Lowercase the bare address out of `Name <a@b>`-style values. */
export function bareAddress(value: string): string {
  const m = value.match(/<([^>]+)>/);
  return (m ? m[1] : value).trim().toLowerCase();
}

/**
 * Pure filter: is this sender on the allowlist? Patterns are exact addresses,
 * `*@domain` (that domain, no subdomains) or `*` for anyone. (unit-tested)
 */
export function addressAllowed(from: string, patterns: string[]): boolean {
  const addr = bareAddress(from);
  return patterns.some((p) => {
    const pat = p.trim().toLowerCase();
    if (pat === "*") return true;
    if (pat.startsWith("*@")) return addr.endsWith(pat.slice(1));
    return addr === pat;
  });
}

/**
 * Pure filter: auto-generated mail (bounces, vacation replies, list blasts)
 * must not wake the agent — replying to an auto-reply is a mail loop.
 */
export function isAutoGenerated(headers: Record<string, string>): boolean {
  const h = new Map(
    Object.entries(headers).map(([k, v]) => [k.toLowerCase(), v.trim().toLowerCase()]),
  );
  const auto = h.get("auto-submitted");
  if (auto && auto !== "no") return true;
  const precedence = h.get("precedence");
  if (precedence && ["bulk", "list", "junk", "auto_reply"].includes(precedence)) return true;
  return false;
}

/**
 * Conversation key for a message: `email:` plus the thread's root Message-ID
 * (the first entry in References, else In-Reply-To, else the message's own id),
 * falling back to normalized subject + counterpart for mail without threading
 * headers. With memory.scope: thread, a correspondence loads its history the
 * way a chat thread does.
 */
export function threadKey(email: ReceivedEmail): string {
  const h = new Map(
    Object.entries(email.headers ?? {}).map(([k, v]) => [k.toLowerCase(), v]),
  );
  const references = h.get("references")?.match(/<[^>]+>/)?.[0];
  const inReplyTo = h.get("in-reply-to")?.match(/<[^>]+>/)?.[0];
  const root = references ?? inReplyTo ?? email.message_id;
  if (root) return `email:${root}`;
  const subject = (email.subject ?? "").replace(/^\s*((re|fwd?):\s*)+/i, "").trim().toLowerCase();
  return `email:${subject}|${bareAddress(email.from)}`;
}

/** Naive tag-strip for HTML-only mail; fine for correspondence, rough on newsletters. */
function stripHtml(html: string): string {
  return html
    .replace(/<(style|script)[\s\S]*?<\/\1>/gi, "")
    .replace(/<br\s*\/?>/gi, "\n")
    .replace(/<\/(p|div|tr|li|h[1-6])>/gi, "\n")
    .replace(/<[^>]+>/g, "")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

/** Render the headers and body of a received email into plain text. */
export function renderEmail(email: ReceivedEmail): string {
  const lines = [
    `From: ${email.from}`,
    `To: ${(email.to ?? []).join(", ")}`,
    `Subject: ${email.subject ?? "(no subject)"}`,
  ];
  if (email.created_at) lines.push(`Date: ${email.created_at}`);
  const body = email.text ?? (email.html ? stripHtml(email.html) : "");
  lines.push("", body.trim());
  return lines.join("\n");
}

/**
 * The prompt and the images for a received email (Plan 14). Images inside the
 * agent's caps reach the model as images; a PDF, an oversized image or one
 * whose bytes don't arrive is a line of prose in the prompt instead. Every
 * transport goes through here, so an attachment is never dropped in silence.
 */
export async function renderEmailInput(
  email: ReceivedEmail,
  limits: MediaLimits,
): Promise<{ input: string; images: ResolvedMedia["images"] }> {
  const { images, notes } = await resolveAttachments(email.attachments ?? [], limits);
  return { input: withNotes(renderEmail(email), notes), images };
}

/** Inputs for {@linkcode verifySvixSignature}. */
export interface SvixVerifyOptions {
  /** The signing secret from the provider (whsec_… — base64 after the prefix). */
  secret: string;
  /** The svix-id header. */
  id: string;
  /** The svix-timestamp header (unix seconds). */
  timestamp: string;
  /** The svix-signature header: space-delimited `v1,<base64>` entries. */
  signature: string;
  /** The raw request body — the signature is over the exact bytes. */
  body: string;
  /** Reject timestamps further than this from now. Defaults to 300s. */
  toleranceSeconds?: number;
  /** Injectable for tests. */
  nowSeconds?: number;
}

/**
 * Verify a Svix-signed webhook request (Resend signs with Svix): HMAC-SHA256
 * over `id.timestamp.body`, base64, compared timing-safe against each listed
 * signature. An unsigned or stale request never reaches the payload parser.
 */
export async function verifySvixSignature(opts: SvixVerifyOptions): Promise<boolean> {
  const now = opts.nowSeconds ?? Date.now() / 1000;
  const tolerance = opts.toleranceSeconds ?? 300;
  const ts = Number(opts.timestamp);
  if (!Number.isFinite(ts) || Math.abs(now - ts) > tolerance) return false;

  let keyBytes: Uint8Array<ArrayBuffer>;
  try {
    keyBytes = Uint8Array.from(atob(opts.secret.replace(/^whsec_/, "")), (c) => c.charCodeAt(0));
  } catch {
    return false;
  }
  const key = await crypto.subtle.importKey(
    "raw",
    keyBytes,
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  );
  const signed = await crypto.subtle.sign(
    "HMAC",
    key,
    new TextEncoder().encode(`${opts.id}.${opts.timestamp}.${opts.body}`),
  );
  const expected = btoa(String.fromCharCode(...new Uint8Array(signed)));

  return opts.signature.split(/\s+/).some((entry) => {
    const [version, sig] = entry.split(",", 2);
    return version === "v1" && sig !== undefined && timingSafeEqual(sig, expected);
  });
}

/** Options for {@linkcode EmailTrigger}. */
export interface EmailTriggerOptions {
  /** URL path the provider POSTs inbound-mail webhooks to. */
  path: string;
  /** TCP port to listen on. */
  port: number;
  /** Webhook signing secret (already resolved from signing_secret_env). */
  signingSecret: string;
  /** Resend API key (already resolved from api_key_env) — fetches bodies, sends replies. */
  apiKey: string;
  /** Senders the agent handles: exact addresses, `*@domain`, or `*`. */
  fromAddresses: string[];
  /** Suppress the reply when the agent answers with the NO_REPLY sentinel (or nothing). */
  allowSilence?: boolean;
  /** Caps on the images an attachment may carry into the context. */
  media: MediaLimits;
  /** Injectable for tests: 0 picks an ephemeral port. */
  onListen?: (addr: { port: number }) => void;
  /** Injectable for tests: the Resend API origin. */
  apiBase?: string;
}

/**
 * Wakes the agent on inbound email pushed by Resend's `email.received`
 * webhook, and sends the agent's reply back through the Resend API as an
 * ordinary email in the same thread.
 */
export class EmailTrigger implements Trigger {
  /** Trigger name, used as the event's `trigger` field. */
  readonly name = "email";
  #opts: EmailTriggerOptions;
  #server?: Deno.HttpServer;
  #inflight = new Set<Promise<void>>();

  /** Create the trigger; no server runs until {@linkcode start}. */
  constructor(opts: EmailTriggerOptions) {
    this.#opts = opts;
  }

  get #apiBase(): string {
    return this.#opts.apiBase ?? RESEND_API;
  }

  /** Start the HTTP server; each verified, allowlisted message wakes the agent. */
  start(emit: (event: AgentEvent) => Promise<RunResult>): Promise<void> {
    const { path, port } = this.#opts;
    this.#server = Deno.serve({
      port,
      onListen: this.#opts.onListen ?? ((addr) => {
        logInfo(`email trigger listening on :${addr.port}${path}`);
      }),
    }, async (req) => {
      const url = new URL(req.url);
      if (url.pathname !== path) return Response.json({ error: "not found" }, { status: 404 });
      if (req.method !== "POST") {
        return Response.json({ error: "method not allowed" }, { status: 405 });
      }

      const body = await req.text();
      const id = req.headers.get("svix-id");
      const timestamp = req.headers.get("svix-timestamp");
      const signature = req.headers.get("svix-signature");
      const verified = id !== null && timestamp !== null && signature !== null &&
        await verifySvixSignature({
          secret: this.#opts.signingSecret,
          id,
          timestamp,
          signature,
          body,
        });
      if (!verified) return Response.json({ error: "invalid signature" }, { status: 401 });

      let event: { type?: unknown; data?: ResendInboundData };
      try {
        event = JSON.parse(body);
      } catch {
        return Response.json({ error: "body must be JSON" }, { status: 400 });
      }
      // Resend sends many event types down one webhook; only inbound mail matters here.
      if (event.type !== "email.received" || !event.data?.email_id) {
        return Response.json({ ignored: String(event.type) });
      }
      const data = event.data;

      // The sender gate runs on webhook metadata, before the body is even
      // fetched — an unlisted sender costs no API call and no model call.
      if (!addressAllowed(data.from, this.#opts.fromAddresses)) {
        logInfo(`email: dropped message from ${data.from} (not in from_addresses)`);
        return Response.json({ ignored: "sender not allowed" });
      }
      // Mail from the agent's own address is its own reply echoed back — a loop.
      if ((data.to ?? []).some((t) => bareAddress(t) === bareAddress(data.from))) {
        return Response.json({ ignored: "own address" });
      }

      // Ack now, run the agent async: the provider retries slow endpoints,
      // and a retried webhook would mean a duplicate run.
      const task = this.#process(data, emit).catch((err) => {
        logError(`email: processing failed: ${(err as Error).message}`);
      });
      this.#inflight.add(task);
      task.finally(() => this.#inflight.delete(task));
      return Response.json({ accepted: true }, { status: 202 });
    });
    return Promise.resolve();
  }

  async #process(
    data: ResendInboundData,
    emit: (event: AgentEvent) => Promise<RunResult>,
  ): Promise<void> {
    // The webhook carries metadata only; the body lives behind the API.
    const res = await fetch(`${this.#apiBase}/emails/receiving/${data.email_id}`, {
      headers: { authorization: `Bearer ${this.#opts.apiKey}` },
    });
    if (!res.ok) {
      await res.body?.cancel();
      throw new Error(`fetching message ${data.email_id} failed (${res.status})`);
    }
    const email = resendToReceived(await res.json());

    if (isAutoGenerated(email.headers ?? {})) {
      logInfo(`email: dropped auto-generated message from ${email.from}`);
      return;
    }

    const { input, images } = await renderEmailInput(email, this.#opts.media);
    const result = await emit({
      id: data.email_id,
      trigger: this.name,
      input,
      images,
      conversationKey: threadKey(email),
    });
    await this.#reply(email, result);
  }

  async #reply(email: ReceivedEmail, result: RunResult): Promise<void> {
    const reply = (result.reply ?? "").trim();

    // The agent had nothing to say — with allow_silence, send nothing.
    if (this.#opts.allowSilence && (reply === NO_REPLY || reply === "")) return;

    // Replies go out from the address the mail arrived on (the agent's own
    // address — the one Resend can send as), back to Reply-To or the sender.
    const from = email.to?.[0];
    if (!from) {
      logError("email: cannot reply — received message has no `to` address");
      return;
    }
    const to = email.reply_to?.[0] ?? email.from;
    const subject = /^re:/i.test(email.subject ?? "")
      ? email.subject!
      : `Re: ${email.subject ?? "(no subject)"}`;

    // In-Reply-To and References make the reply land in the same thread.
    const headers: Record<string, string> = {};
    if (email.message_id) {
      headers["In-Reply-To"] = email.message_id;
      const prior = Object.entries(email.headers ?? {})
        .find(([k]) => k.toLowerCase() === "references")?.[1];
      headers["References"] = prior ? `${prior} ${email.message_id}` : email.message_id;
    }

    const res = await fetch(`${this.#apiBase}/emails`, {
      method: "POST",
      headers: {
        authorization: `Bearer ${this.#opts.apiKey}`,
        "content-type": "application/json",
      },
      body: JSON.stringify({
        from,
        to: [to],
        subject,
        text: reply || `(${result.status})`,
        ...(Object.keys(headers).length ? { headers } : {}),
      }),
    });
    if (!res.ok) {
      logError(`email: reply failed (${res.status}): ${await res.text()}`);
    } else {
      await res.body?.cancel();
    }
  }

  /** Shut down the HTTP server and wait for in-flight runs to finish. */
  async stop(): Promise<void> {
    await this.#server?.shutdown();
    await Promise.allSettled([...this.#inflight]);
  }
}
