import type { AgentEvent, RunResult, Trigger } from "@looped/core";
import { NO_REPLY } from "./text.ts";
import {
  addressAllowed,
  bareAddress,
  isAutoGenerated,
  type ReceivedEmail,
  renderEmail,
} from "./email.ts";

// The Gmail pulled transport (Plan 7, phase 3): poll the Gmail API for unread
// messages in a label, authenticated by an OAuth refresh token minted outside
// the container (the image has no browser — docs/email.mdx documents the
// one-time flow). The unread state is the cursor, same story as the IMAP
// transport's \Seen flag: handled and dropped messages get UNREAD removed, so
// route mail to the agent's label with Gmail filters and let it own that label.

const GMAIL_API = "https://gmail.googleapis.com";
const GOOGLE_TOKEN_URL = "https://oauth2.googleapis.com/token";

interface GmailPayload {
  mimeType?: string;
  filename?: string;
  headers?: { name: string; value: string }[];
  body?: { data?: string; size?: number };
  parts?: GmailPayload[];
}

function base64UrlDecode(data: string): string {
  const b64 = data.replace(/-/g, "+").replace(/_/g, "/");
  const bytes = Uint8Array.from(atob(b64), (c) => c.charCodeAt(0));
  return new TextDecoder().decode(bytes);
}

function base64UrlEncode(s: string): string {
  const b64 = btoa(String.fromCharCode(...new TextEncoder().encode(s)));
  return b64.replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

/** Flatten a Gmail message payload into headers, bodies and attachment metadata. */
export function gmailToReceived(payload: GmailPayload): ReceivedEmail {
  const headers: Record<string, string> = {};
  for (const h of payload.headers ?? []) {
    const name = h.name.toLowerCase();
    if (!(name in headers)) headers[name] = h.value;
  }
  const received: ReceivedEmail = {
    from: headers["from"] ?? "",
    to: headers["to"] ? [headers["to"]] : [],
    reply_to: headers["reply-to"] ? [headers["reply-to"]] : [],
    subject: headers["subject"],
    created_at: headers["date"],
    headers,
    message_id: headers["message-id"],
    attachments: [],
  };
  const walk = (part: GmailPayload) => {
    if (part.parts) {
      for (const p of part.parts) walk(p);
      return;
    }
    if (part.filename) {
      received.attachments!.push({
        filename: part.filename,
        content_type: part.mimeType,
        size: part.body?.size,
      });
      return;
    }
    if (part.body?.data && part.mimeType === "text/plain") {
      received.text ??= base64UrlDecode(part.body.data);
    } else if (part.body?.data && part.mimeType === "text/html") {
      received.html ??= base64UrlDecode(part.body.data);
    }
  };
  walk(payload);
  return received;
}

/** Options for {@linkcode GmailEmailTrigger}. */
export interface GmailEmailTriggerOptions {
  /** OAuth client id (a Google Cloud "Desktop app" client). */
  clientId: string;
  /** OAuth client secret (already resolved from client_secret_env). */
  clientSecret: string;
  /** Refresh token from the one-time consent flow (already resolved from refresh_token_env). */
  refreshToken: string;
  /** Gmail label to watch. */
  label: string;
  /** Seconds between polls. */
  pollSeconds: number;
  /** Senders the agent handles: exact addresses, `*@domain`, or `*`. */
  fromAddresses: string[];
  /** Suppress the reply when the agent answers with the NO_REPLY sentinel (or nothing). */
  allowSilence?: boolean;
  /** Injectable for tests: the Gmail API origin. */
  apiBase?: string;
  /** Injectable for tests: the OAuth token endpoint. */
  tokenUrl?: string;
}

/**
 * Polls the Gmail API for unread messages in a label, wakes the agent on the
 * ones that pass the filters and sends replies into the same Gmail thread.
 */
export class GmailEmailTrigger implements Trigger {
  /** Trigger name, used as the event's `trigger` field. */
  readonly name = "email";
  #opts: GmailEmailTriggerOptions;
  #stopped = false;
  #backoffMs = 1_000;
  #wake?: () => void;
  #token?: { value: string; expiresAt: number };
  #self = "";

  /** Create the trigger; nothing connects until {@linkcode start}. */
  constructor(opts: GmailEmailTriggerOptions) {
    this.#opts = opts;
  }

  async #accessToken(): Promise<string> {
    if (this.#token && Date.now() < this.#token.expiresAt - 60_000) return this.#token.value;
    const res = await fetch(this.#opts.tokenUrl ?? GOOGLE_TOKEN_URL, {
      method: "POST",
      headers: { "content-type": "application/x-www-form-urlencoded" },
      body: new URLSearchParams({
        client_id: this.#opts.clientId,
        client_secret: this.#opts.clientSecret,
        refresh_token: this.#opts.refreshToken,
        grant_type: "refresh_token",
      }),
    });
    if (!res.ok) {
      const detail = await res.text();
      throw new Error(`gmail: token refresh failed (${res.status}): ${detail.slice(0, 200)}`);
    }
    const body = await res.json();
    this.#token = { value: body.access_token, expiresAt: Date.now() + body.expires_in * 1_000 };
    return this.#token.value;
  }

  async #api(path: string, init?: RequestInit): Promise<Response> {
    const token = await this.#accessToken();
    const res = await fetch(`${this.#opts.apiBase ?? GMAIL_API}${path}`, {
      ...init,
      headers: { ...init?.headers, authorization: `Bearer ${token}` },
    });
    if (res.status === 401) {
      this.#token = undefined; // stale token; the next cycle refreshes
      await res.body?.cancel();
      throw new Error("gmail: API returned 401; refreshing the access token");
    }
    if (!res.ok) {
      const detail = await res.text();
      throw new Error(
        `gmail: ${path.split("?")[0]} failed (${res.status}): ${detail.slice(0, 200)}`,
      );
    }
    return res;
  }

  /** Mint a token, learn the account's address and start the poll loop. */
  async start(emit: (event: AgentEvent) => Promise<RunResult>): Promise<void> {
    // A bad refresh token fails the boot here, ahead of the first message.
    const profile = await (await this.#api("/gmail/v1/users/me/profile")).json();
    this.#self = String(profile.emailAddress ?? "").toLowerCase();
    console.log(`email trigger (gmail) watching label ${this.#opts.label} of ${this.#self}`);
    this.#loop(emit); // poll loop runs for the service's lifetime
  }

  async #loop(emit: (event: AgentEvent) => Promise<RunResult>): Promise<void> {
    while (!this.#stopped) {
      try {
        await this.#pollOnce(emit);
        this.#backoffMs = 1_000;
      } catch (err) {
        if (this.#stopped) return;
        const delay = this.#backoffMs;
        this.#backoffMs = Math.min(delay * 2, 60_000);
        console.log(
          `email (gmail): poll error (${(err as Error).message}), retrying in ${delay}ms`,
        );
        await this.#sleep(delay);
        continue;
      }
      await this.#sleep(this.#opts.pollSeconds * 1_000);
    }
  }

  #sleep(ms: number): Promise<void> {
    return new Promise((resolve) => {
      const timer = setTimeout(resolve, ms);
      this.#wake = () => {
        clearTimeout(timer);
        resolve();
      };
    });
  }

  async #pollOnce(emit: (event: AgentEvent) => Promise<RunResult>): Promise<void> {
    const q = encodeURIComponent(`label:${this.#opts.label} is:unread`);
    const list = await (await this.#api(`/gmail/v1/users/me/messages?q=${q}&maxResults=25`)).json();

    for (const m of list.messages ?? []) {
      if (this.#stopped) return;
      const markRead = () =>
        this.#api(`/gmail/v1/users/me/messages/${m.id}/modify`, {
          method: "POST",
          headers: { "content-type": "application/json" },
          body: JSON.stringify({ removeLabelIds: ["UNREAD"] }),
        }).then((r) => r.body?.cancel());

      const full = await (await this.#api(`/gmail/v1/users/me/messages/${m.id}?format=full`))
        .json();
      const received = gmailToReceived(full.payload ?? {});

      const own = bareAddress(received.from) === this.#self;
      if (
        own || !addressAllowed(received.from, this.#opts.fromAddresses) ||
        isAutoGenerated(received.headers ?? {})
      ) {
        if (!own && !isAutoGenerated(received.headers ?? {})) {
          console.log(
            `email (gmail): dropped message from ${received.from} (not in from_addresses)`,
          );
        }
        await markRead(); // still advance the cursor, or every poll refetches it
        continue;
      }

      const result = await emit({
        id: m.id,
        trigger: this.name,
        input: renderEmail(received),
        // Gmail's own thread id is stable and matches where the reply lands.
        conversationKey: `email:gmail:${full.threadId}`,
      });
      await this.#reply(received, full.threadId, result);
      await markRead(); // after the run: the unread state is the cursor
    }
  }

  async #reply(email: ReceivedEmail, threadId: string, result: RunResult): Promise<void> {
    const reply = (result.reply ?? "").trim();
    if (this.#opts.allowSilence && (reply === NO_REPLY || reply === "")) return;

    const subject = /^re:/i.test(email.subject ?? "")
      ? email.subject!
      : `Re: ${email.subject ?? "(no subject)"}`;
    const raw = [
      `From: ${this.#self}`,
      `To: ${email.reply_to?.[0] || email.from}`,
      `Subject: ${subject}`,
      ...(email.message_id
        ? [
          `In-Reply-To: ${email.message_id}`,
          `References: ${
            [email.headers?.["references"], email.message_id].filter(Boolean).join(" ")
          }`,
        ]
        : []),
      "Content-Type: text/plain; charset=utf-8",
      "",
      reply || `(${result.status})`,
    ].join("\r\n");

    try {
      const res = await this.#api("/gmail/v1/users/me/messages/send", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ raw: base64UrlEncode(raw), threadId }),
      });
      await res.body?.cancel();
    } catch (err) {
      console.error(`email (gmail): reply failed: ${(err as Error).message}`);
    }
  }

  /** Stop the poll loop; the current cycle finishes its message first. */
  stop(): Promise<void> {
    this.#stopped = true;
    this.#wake?.();
    return Promise.resolve();
  }
}
