import { assert, assertEquals, assertThrows } from "@std/assert";
import type { AgentEvent, RunResult } from "@looped/core";
import { parseAgentConfig } from "@looped/core";
import {
  addressAllowed,
  EmailTrigger,
  isAutoGenerated,
  renderEmail,
  type ResendReceivedEmail,
  threadKey,
  verifySvixSignature,
} from "./email.ts";
import { triggersFromConfig } from "./mod.ts";
import { NO_REPLY } from "./text.ts";

// ---------------------------------------------------------------------------
// Pure filters

Deno.test("addressAllowed: exact match, case-insensitive, display-name form", () => {
  const patterns = ["petra@example.com"];
  assert(addressAllowed("petra@example.com", patterns));
  assert(addressAllowed("Petra@Example.COM", patterns));
  assert(addressAllowed("Petra Lang <petra@example.com>", patterns));
  assert(!addressAllowed("someone@example.com", patterns));
});

Deno.test("addressAllowed: *@domain matches the domain, no subdomains, * matches anyone", () => {
  assert(addressAllowed("anyone@example.com", ["*@example.com"]));
  assert(!addressAllowed("anyone@mail.example.com", ["*@example.com"]));
  assert(!addressAllowed("anyone@notexample.com", ["*@example.com"]));
  assert(addressAllowed("total@stranger.net", ["*"]));
});

Deno.test("isAutoGenerated: Auto-Submitted and bulk Precedence drop; normal mail passes", () => {
  assert(isAutoGenerated({ "Auto-Submitted": "auto-replied" }));
  assert(isAutoGenerated({ "auto-submitted": "auto-generated" }));
  assert(!isAutoGenerated({ "Auto-Submitted": "no" }));
  assert(isAutoGenerated({ Precedence: "bulk" }));
  assert(isAutoGenerated({ precedence: "list" }));
  assert(!isAutoGenerated({ Precedence: "first-class" }));
  assert(!isAutoGenerated({}));
});

Deno.test("threadKey: root Message-ID from References, then In-Reply-To, then own id", () => {
  const base: ResendReceivedEmail = { from: "petra@example.com", message_id: "<own@ex>" };
  assertEquals(
    threadKey({
      ...base,
      headers: { References: "<root@ex> <mid@ex>", "In-Reply-To": "<mid@ex>" },
    }),
    "email:<root@ex>",
  );
  assertEquals(threadKey({ ...base, headers: { "in-reply-to": "<mid@ex>" } }), "email:<mid@ex>");
  assertEquals(threadKey(base), "email:<own@ex>");
});

Deno.test("threadKey: fallback normalizes subject and counterpart", () => {
  const a = threadKey({ from: "petra@example.com", subject: "Invoice 42" });
  const b = threadKey({ from: "Petra <PETRA@example.com>", subject: "Re: re: invoice 42" });
  assertEquals(a, b);
  assertEquals(a, "email:invoice 42|petra@example.com");
});

Deno.test("renderEmail: headers, text body, attachment listing; HTML fallback strips tags", () => {
  const text = renderEmail({
    from: "petra@example.com",
    to: ["agent@example.com"],
    subject: "Invoice 42",
    created_at: "2026-07-07T09:00:00Z",
    text: "Please file this.",
    attachments: [{ filename: "invoice.pdf", content_type: "application/pdf", size: 1234 }],
  });
  assert(text.includes("From: petra@example.com"));
  assert(text.includes("Subject: Invoice 42"));
  assert(text.includes("Please file this."));
  assert(text.includes("[attachment: invoice.pdf (application/pdf, 1234 bytes) — not delivered]"));

  const html = renderEmail({
    from: "a@b.c",
    html: "<div><p>Hello &amp; welcome</p><br><script>evil()</script></div>",
  });
  assert(html.includes("Hello & welcome"));
  assert(!html.includes("evil"));
  assert(!html.includes("<p>"));
});

// ---------------------------------------------------------------------------
// Signature verification

const SECRET = "whsec_" + btoa("test-signing-key");

async function sign(id: string, timestamp: string, body: string): Promise<string> {
  const key = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode("test-signing-key"),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  );
  const sig = await crypto.subtle.sign(
    "HMAC",
    key,
    new TextEncoder().encode(`${id}.${timestamp}.${body}`),
  );
  return btoa(String.fromCharCode(...new Uint8Array(sig)));
}

Deno.test("verifySvixSignature: valid signature passes, tampered body fails", async () => {
  const now = 1_750_000_000;
  const body = '{"type":"email.received"}';
  const sig = await sign("msg_1", String(now), body);
  const base = { secret: SECRET, id: "msg_1", timestamp: String(now), nowSeconds: now };
  assert(await verifySvixSignature({ ...base, signature: `v1,${sig}`, body }));
  // Additional unknown signatures are fine as long as one v1 entry matches.
  assert(await verifySvixSignature({ ...base, signature: `v2,bogus v1,${sig}`, body }));
  assert(!await verifySvixSignature({ ...base, signature: `v1,${sig}`, body: body + " " }));
  assert(!await verifySvixSignature({ ...base, signature: "v1,bm90LXRoZS1zaWc=", body }));
});

Deno.test("verifySvixSignature: stale timestamps are rejected", async () => {
  const now = 1_750_000_000;
  const body = "{}";
  const stale = String(now - 3600);
  const sig = await sign("msg_1", stale, body);
  assert(
    !await verifySvixSignature({
      secret: SECRET,
      id: "msg_1",
      timestamp: stale,
      signature: `v1,${sig}`,
      body,
      nowSeconds: now,
    }),
  );
});

// ---------------------------------------------------------------------------
// The trigger end to end, against a fake Resend API

const RECEIVED: ResendReceivedEmail = {
  from: "Petra Lang <petra@example.com>",
  to: ["agent@example.com"],
  reply_to: [],
  subject: "Invoice 42",
  created_at: "2026-07-07T09:00:00Z",
  text: "Please file the attached invoice.",
  headers: { "Message-Id": "<orig@example.com>" },
  message_id: "<orig@example.com>",
};

/** A fake api.resend.com: serves the received email, captures reply sends. */
function fakeResendApi(email: ResendReceivedEmail) {
  const sent: { body: Record<string, unknown> }[] = [];
  let port = 0;
  const server = Deno.serve({ port: 0, onListen: (a) => (port = a.port) }, async (req) => {
    const url = new URL(req.url);
    if (req.method === "GET" && url.pathname.startsWith("/emails/receiving/")) {
      return Response.json(email);
    }
    if (req.method === "POST" && url.pathname === "/emails") {
      sent.push({ body: await req.json() });
      return Response.json({ id: "sent_1" });
    }
    return Response.json({ error: "unexpected" }, { status: 500 });
  });
  return { sent, apiBase: () => `http://127.0.0.1:${port}`, close: () => server.shutdown() };
}

function runResult(reply: string): RunResult {
  return {
    status: "ok",
    reply,
    steps: 1,
    usage: { inputTokens: 1, outputTokens: 1 },
    messages: [],
  };
}

async function startTrigger(
  api: { apiBase: () => string },
  emit: (event: AgentEvent) => Promise<RunResult>,
  overrides: Partial<ConstructorParameters<typeof EmailTrigger>[0]> = {},
) {
  let port = 0;
  const trigger = new EmailTrigger({
    path: "/email",
    port: 0,
    signingSecret: SECRET,
    apiKey: "re_test",
    fromAddresses: ["*@example.com"],
    onListen: (a) => (port = a.port),
    apiBase: api.apiBase(),
    ...overrides,
  });
  await trigger.start(emit);
  return { trigger, url: () => `http://127.0.0.1:${port}/email` };
}

async function postWebhook(url: string, payload: unknown, opts: { badSig?: boolean } = {}) {
  const body = JSON.stringify(payload);
  const timestamp = String(Math.floor(Date.now() / 1000));
  const sig = opts.badSig ? "Zm9yZ2Vk" : await sign("msg_1", timestamp, body);
  return await fetch(url, {
    method: "POST",
    headers: {
      "content-type": "application/json",
      "svix-id": "msg_1",
      "svix-timestamp": timestamp,
      "svix-signature": `v1,${sig}`,
    },
    body,
  });
}

const INBOUND = {
  type: "email.received",
  data: {
    email_id: "rcv_1",
    from: "Petra Lang <petra@example.com>",
    to: ["agent@example.com"],
    subject: "Invoice 42",
    message_id: "<orig@example.com>",
  },
};

Deno.test("email: verified webhook wakes the agent and the reply threads back", async () => {
  const api = fakeResendApi(RECEIVED);
  const events: AgentEvent[] = [];
  const { trigger, url } = await startTrigger(api, (event) => {
    events.push(event);
    return Promise.resolve(runResult("Filed it."));
  });

  // Unsigned/forged POSTs never reach the parser.
  const forged = await postWebhook(url(), INBOUND, { badSig: true });
  assertEquals(forged.status, 401);
  await forged.body?.cancel();

  const res = await postWebhook(url(), INBOUND);
  assertEquals(res.status, 202);
  await res.body?.cancel();

  await trigger.stop(); // drains the in-flight run
  await api.close();

  assertEquals(events.length, 1);
  assert(events[0].input.includes("Subject: Invoice 42"));
  assert(events[0].input.includes("Please file the attached invoice."));
  assertEquals(events[0].conversationKey, "email:<orig@example.com>");

  assertEquals(api.sent.length, 1);
  const reply = api.sent[0].body;
  assertEquals(reply.from, "agent@example.com");
  assertEquals(reply.to, ["Petra Lang <petra@example.com>"]);
  assertEquals(reply.subject, "Re: Invoice 42");
  assertEquals(reply.text, "Filed it.");
  assertEquals((reply.headers as Record<string, string>)["In-Reply-To"], "<orig@example.com>");
});

Deno.test("email: unlisted senders and foreign event types are ignored without a run", async () => {
  const api = fakeResendApi(RECEIVED);
  let runs = 0;
  const { trigger, url } = await startTrigger(api, () => {
    runs++;
    return Promise.resolve(runResult("nope"));
  }, { fromAddresses: ["only@this-address.com"] });

  const stranger = await postWebhook(url(), INBOUND);
  assertEquals(stranger.status, 200);
  assertEquals((await stranger.json()).ignored, "sender not allowed");

  const delivered = await postWebhook(url(), { type: "email.delivered", data: { email_id: "x" } });
  assertEquals(delivered.status, 200);
  await delivered.body?.cancel();

  await trigger.stop();
  await api.close();
  assertEquals(runs, 0);
  assertEquals(api.sent.length, 0);
});

Deno.test("email: auto-generated mail is dropped after the body fetch", async () => {
  const api = fakeResendApi({ ...RECEIVED, headers: { "Auto-Submitted": "auto-replied" } });
  let runs = 0;
  const { trigger, url } = await startTrigger(api, () => {
    runs++;
    return Promise.resolve(runResult("nope"));
  });
  const res = await postWebhook(url(), INBOUND);
  assertEquals(res.status, 202);
  await res.body?.cancel();
  await trigger.stop();
  await api.close();
  assertEquals(runs, 0);
});

Deno.test("email: allow_silence sends nothing on NO_REPLY", async () => {
  const api = fakeResendApi(RECEIVED);
  const { trigger, url } = await startTrigger(
    api,
    () => Promise.resolve(runResult(NO_REPLY)),
    { allowSilence: true },
  );
  const res = await postWebhook(url(), INBOUND);
  assertEquals(res.status, 202);
  await res.body?.cancel();
  await trigger.stop();
  await api.close();
  assertEquals(api.sent.length, 0);
});

// ---------------------------------------------------------------------------
// Config wiring

const EMAIL_CONFIG = parseAgentConfig(`
handle: mail-bot
description: email trigger test agent
model:
  provider: openai-compatible
  id: test-model
purpose: test
triggers:
  - type: email
    transport: resend
    from_addresses: ["*@example.com"]
`);

Deno.test("triggersFromConfig: builds the email trigger, fails loudly on missing secrets", () => {
  const env: Record<string, string> = {
    RESEND_WEBHOOK_SECRET: "whsec_abc",
    RESEND_API_KEY: "re_123",
  };
  const triggers = triggersFromConfig(EMAIL_CONFIG, (n) => env[n]);
  assertEquals(triggers.map((t) => t.name), ["email"]);

  const without = (name: string) => (n: string) => n === name ? undefined : env[n];
  assertThrows(
    () => triggersFromConfig(EMAIL_CONFIG, without("RESEND_WEBHOOK_SECRET")),
    Error,
    "RESEND_WEBHOOK_SECRET",
  );
  assertThrows(
    () => triggersFromConfig(EMAIL_CONFIG, without("RESEND_API_KEY")),
    Error,
    "RESEND_API_KEY",
  );
});

Deno.test("config: from_addresses is required and defaults apply", () => {
  const err = assertThrows(() =>
    parseAgentConfig(`
handle: mail-bot
description: x
model:
  provider: openai-compatible
  id: test-model
purpose: test
triggers:
  - type: email
    transport: resend
`)
  );
  assert(String(err).includes("from_addresses"));

  const t = EMAIL_CONFIG.triggers![0];
  if (t.type !== "email") throw new Error("expected email trigger");
  assertEquals(t.path, "/email");
  assertEquals(t.port, 8080);
  assertEquals(t.signing_secret_env, "RESEND_WEBHOOK_SECRET");
  assertEquals(t.api_key_env, "RESEND_API_KEY");
  assertEquals(t.allow_silence, false);
});
