import type { AgentEvent, RunResult, Trigger } from "@looped/core";
import { NO_REPLY } from "./text.ts";
import {
  addressAllowed,
  bareAddress,
  isAutoGenerated,
  type ReceivedEmail,
  renderEmail,
} from "./email.ts";

// The Outlook pulled transport (Plan 7, phase 3): poll Microsoft Graph for
// unread messages in a folder, authenticated by an OAuth refresh token from
// the one-time device-code flow (docs/email.mdx documents it). isRead is the
// cursor, same story as the other pulled transports.
//
// One Microsoft-specific wrinkle: Graph rotates refresh tokens — each refresh
// response may carry a new one, and the trigger keeps the latest in memory.
// The env var holds the original; after a long outage the operator may need
// to run the device-code flow again.

const GRAPH_API = "https://graph.microsoft.com/v1.0";
const GRAPH_SCOPE = "https://graph.microsoft.com/Mail.ReadWrite " +
  "https://graph.microsoft.com/Mail.Send offline_access";

interface GraphRecipient {
  emailAddress?: { name?: string; address?: string };
}

interface GraphMessage {
  id: string;
  conversationId?: string;
  subject?: string;
  from?: GraphRecipient;
  toRecipients?: GraphRecipient[];
  replyTo?: GraphRecipient[];
  receivedDateTime?: string;
  body?: { contentType?: string; content?: string };
  internetMessageHeaders?: { name: string; value: string }[];
  attachments?: { name?: string; contentType?: string; size?: number }[];
}

function formatAddress(r: GraphRecipient | undefined): string {
  const address = r?.emailAddress?.address ?? "";
  const name = r?.emailAddress?.name;
  return name && name !== address ? `${name} <${address}>` : address;
}

/** Map a Graph message into the shared received-email shape. */
export function graphToReceived(msg: GraphMessage): ReceivedEmail {
  const headers: Record<string, string> = {};
  for (const h of msg.internetMessageHeaders ?? []) {
    const name = h.name.toLowerCase();
    if (!(name in headers)) headers[name] = h.value;
  }
  const html = msg.body?.contentType?.toLowerCase() === "html" ? msg.body?.content : undefined;
  return {
    from: formatAddress(msg.from),
    to: (msg.toRecipients ?? []).map(formatAddress),
    reply_to: (msg.replyTo ?? []).map(formatAddress),
    subject: msg.subject,
    created_at: msg.receivedDateTime,
    text: html ? undefined : msg.body?.content,
    html,
    headers,
    message_id: headers["message-id"],
    attachments: (msg.attachments ?? []).map((a) => ({
      filename: a.name,
      content_type: a.contentType,
      size: a.size,
    })),
  };
}

/** Options for {@linkcode OutlookEmailTrigger}. */
export interface OutlookEmailTriggerOptions {
  /** The app registration's client id. */
  clientId: string;
  /** Client secret for confidential clients; public (device-code) clients have none. */
  clientSecret?: string;
  /** Refresh token from the one-time device-code flow (already resolved from refresh_token_env). */
  refreshToken: string;
  /** Entra tenant: "common", "consumers", "organizations" or a tenant id. */
  tenant: string;
  /** Mail folder to watch: a well-known name (inbox) or a folder id. */
  folder: string;
  /** Seconds between polls. */
  pollSeconds: number;
  /** Senders the agent handles: exact addresses, `*@domain`, or `*`. */
  fromAddresses: string[];
  /** Suppress the reply when the agent answers with the NO_REPLY sentinel (or nothing). */
  allowSilence?: boolean;
  /** Injectable for tests: the Graph API origin (including version prefix). */
  apiBase?: string;
  /** Injectable for tests: the OAuth token endpoint. */
  tokenUrl?: string;
}

/**
 * Polls Microsoft Graph for unread messages in a folder, wakes the agent on
 * the ones that pass the filters and replies into the same conversation.
 */
export class OutlookEmailTrigger implements Trigger {
  /** Trigger name, used as the event's `trigger` field. */
  readonly name = "email";
  #opts: OutlookEmailTriggerOptions;
  #stopped = false;
  #backoffMs = 1_000;
  #wake?: () => void;
  #token?: { value: string; expiresAt: number };
  #refreshToken: string;
  #self = "";

  /** Create the trigger; nothing connects until {@linkcode start}. */
  constructor(opts: OutlookEmailTriggerOptions) {
    this.#opts = opts;
    this.#refreshToken = opts.refreshToken;
  }

  async #accessToken(): Promise<string> {
    if (this.#token && Date.now() < this.#token.expiresAt - 60_000) return this.#token.value;
    const tokenUrl = this.#opts.tokenUrl ??
      `https://login.microsoftonline.com/${this.#opts.tenant}/oauth2/v2.0/token`;
    const params = new URLSearchParams({
      client_id: this.#opts.clientId,
      grant_type: "refresh_token",
      refresh_token: this.#refreshToken,
      scope: GRAPH_SCOPE,
    });
    if (this.#opts.clientSecret) params.set("client_secret", this.#opts.clientSecret);
    const res = await fetch(tokenUrl, {
      method: "POST",
      headers: { "content-type": "application/x-www-form-urlencoded" },
      body: params,
    });
    if (!res.ok) {
      const detail = await res.text();
      throw new Error(`outlook: token refresh failed (${res.status}): ${detail.slice(0, 200)}`);
    }
    const body = await res.json();
    this.#token = { value: body.access_token, expiresAt: Date.now() + body.expires_in * 1_000 };
    if (body.refresh_token) this.#refreshToken = body.refresh_token; // Graph rotates these
    return this.#token.value;
  }

  async #api(path: string, init?: RequestInit): Promise<Response> {
    const token = await this.#accessToken();
    const res = await fetch(`${this.#opts.apiBase ?? GRAPH_API}${path}`, {
      ...init,
      headers: { ...init?.headers, authorization: `Bearer ${token}` },
    });
    if (res.status === 401) {
      this.#token = undefined; // stale token; the next cycle refreshes
      await res.body?.cancel();
      throw new Error("outlook: API returned 401; refreshing the access token");
    }
    if (!res.ok) {
      const detail = await res.text();
      throw new Error(
        `outlook: ${path.split("?")[0]} failed (${res.status}): ${detail.slice(0, 200)}`,
      );
    }
    return res;
  }

  /** Mint a token, learn the account's address and start the poll loop. */
  async start(emit: (event: AgentEvent) => Promise<RunResult>): Promise<void> {
    // A bad refresh token fails the boot here, ahead of the first message.
    const me = await (await this.#api("/me?$select=mail,userPrincipalName")).json();
    this.#self = String(me.mail ?? me.userPrincipalName ?? "").toLowerCase();
    console.log(`email trigger (outlook) watching ${this.#opts.folder} of ${this.#self}`);
    this.#loop(emit); // poll loop runs for the service's lifetime
  }

  async #loop(emit: (event: AgentEvent) => Promise<RunResult>): Promise<void> {
    while (!this.#stopped) {
      try {
        await this.#pollOnce(emit);
        this.#backoffMs = 1_000;
      } catch (err) {
        if (this.#stopped) return;
        const delay = this.#backoffMs;
        this.#backoffMs = Math.min(delay * 2, 60_000);
        console.log(
          `email (outlook): poll error (${(err as Error).message}), retrying in ${delay}ms`,
        );
        await this.#sleep(delay);
        continue;
      }
      await this.#sleep(this.#opts.pollSeconds * 1_000);
    }
  }

  #sleep(ms: number): Promise<void> {
    return new Promise((resolve) => {
      const timer = setTimeout(resolve, ms);
      this.#wake = () => {
        clearTimeout(timer);
        resolve();
      };
    });
  }

  async #pollOnce(emit: (event: AgentEvent) => Promise<RunResult>): Promise<void> {
    const select = "id,conversationId,subject,from,toRecipients,replyTo,receivedDateTime,body," +
      "internetMessageHeaders";
    const path = `/me/mailFolders/${encodeURIComponent(this.#opts.folder)}/messages` +
      `?$filter=${encodeURIComponent("isRead eq false")}&$top=25` +
      `&$select=${encodeURIComponent(select)}` +
      `&$expand=${encodeURIComponent("attachments($select=name,contentType,size)")}`;
    const list = await (await this.#api(path)).json();

    for (const msg of (list.value ?? []) as GraphMessage[]) {
      if (this.#stopped) return;
      const markRead = () =>
        this.#api(`/me/messages/${msg.id}`, {
          method: "PATCH",
          headers: { "content-type": "application/json" },
          body: JSON.stringify({ isRead: true }),
        }).then((r) => r.body?.cancel());

      const received = graphToReceived(msg);
      const own = bareAddress(received.from) === this.#self;
      if (
        own || !addressAllowed(received.from, this.#opts.fromAddresses) ||
        isAutoGenerated(received.headers ?? {})
      ) {
        if (!own && !isAutoGenerated(received.headers ?? {})) {
          console.log(
            `email (outlook): dropped message from ${received.from} (not in from_addresses)`,
          );
        }
        await markRead(); // still advance the cursor, or every poll refetches it
        continue;
      }

      const result = await emit({
        id: msg.id,
        trigger: this.name,
        input: renderEmail(received),
        // Graph's conversation id is stable and matches where the reply lands.
        conversationKey: `email:outlook:${msg.conversationId ?? msg.id}`,
      });
      await this.#reply(msg.id, result);
      await markRead(); // after the run: the unread state is the cursor
    }
  }

  async #reply(messageId: string, result: RunResult): Promise<void> {
    const reply = (result.reply ?? "").trim();
    if (this.#opts.allowSilence && (reply === NO_REPLY || reply === "")) return;
    try {
      // Graph's reply endpoint threads, addresses and quotes for us.
      const res = await this.#api(`/me/messages/${messageId}/reply`, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ comment: reply || `(${result.status})` }),
      });
      await res.body?.cancel();
    } catch (err) {
      console.error(`email (outlook): reply failed: ${(err as Error).message}`);
    }
  }

  /** Stop the poll loop; the current cycle finishes its message first. */
  stop(): Promise<void> {
    this.#stopped = true;
    this.#wake?.();
    return Promise.resolve();
  }
}
