import { logError, logInfo } from "@looped/core";
import type { AgentEvent, MediaLimits, RunResult, Trigger } from "@looped/core";
import { NO_REPLY } from "./text.ts";
import {
  addressAllowed,
  bareAddress,
  isAutoGenerated,
  type ReceivedEmail,
  renderEmailInput,
  threadKey,
} from "./email.ts";
import { parseMime } from "./mime.ts";

// The pulled email transport (Plan 7, phase 2): sign into a mailbox that
// already exists and poll it. Like the Telegram trigger, the client here is
// deliberately minimal — the handful of IMAP commands this loop needs and an
// SMTP send for replies, no library (Plan 0, principle 8).
//
// The mailbox itself is the cursor: the loop fetches messages the mailbox
// marks unseen and flags them \Seen when done. A restarted container picks up
// where it left off with no local state; a crash between the run and the flag
// write costs one duplicate run. Dropped messages (unlisted sender, auto-mail)
// are flagged immediately, or every poll would refetch them. The agent shares
// read-state with any human in the same mailbox, so give it a dedicated
// address or folder.

const CRLF = "\r\n";

/** A buffered line/byte reader over a TCP or TLS connection. */
class TextConn {
  #conn: Deno.Conn;
  #buf = new Uint8Array(0);
  #decoder = new TextDecoder("latin1");

  constructor(conn: Deno.Conn) {
    this.#conn = conn;
  }

  async #fill(): Promise<void> {
    const chunk = new Uint8Array(16 * 1024);
    const n = await this.#conn.read(chunk);
    if (n === null) throw new Error("connection closed");
    const merged = new Uint8Array(this.#buf.length + n);
    merged.set(this.#buf);
    merged.set(chunk.subarray(0, n), this.#buf.length);
    this.#buf = merged;
  }

  /** Read one CRLF-terminated line (returned without the terminator). */
  async readLine(): Promise<string> {
    for (;;) {
      const nl = this.#buf.indexOf(0x0a);
      if (nl !== -1) {
        const end = nl > 0 && this.#buf[nl - 1] === 0x0d ? nl - 1 : nl;
        const line = this.#decoder.decode(this.#buf.subarray(0, end));
        this.#buf = this.#buf.subarray(nl + 1);
        return line;
      }
      await this.#fill();
    }
  }

  /** Read exactly n bytes (an IMAP literal). */
  async readBytes(n: number): Promise<Uint8Array> {
    while (this.#buf.length < n) await this.#fill();
    const bytes = this.#buf.subarray(0, n);
    this.#buf = this.#buf.subarray(n);
    return bytes;
  }

  async write(s: string): Promise<void> {
    const bytes = new TextEncoder().encode(s);
    let written = 0;
    while (written < bytes.length) {
      written += await this.#conn.write(bytes.subarray(written));
    }
  }

  close(): void {
    try {
      this.#conn.close();
    } catch {
      // already closed
    }
  }
}

interface ImapResponse {
  ok: boolean;
  /** The tagged completion line's text (after OK/NO/BAD). */
  text: string;
  /** Untagged `* ...` lines, each with the literal that followed it, if any. */
  untagged: { line: string; literal?: Uint8Array }[];
}

/** The IMAP subset the poll loop needs: LOGIN, SELECT, UID SEARCH/FETCH/STORE. */
class ImapSession {
  #c: TextConn;
  #tag = 0;

  private constructor(c: TextConn) {
    this.#c = c;
  }

  static async connect(
    opts: { host: string; port: number; tls: boolean },
  ): Promise<ImapSession> {
    const conn = opts.tls
      ? await Deno.connectTls({ hostname: opts.host, port: opts.port })
      : await Deno.connect({ hostname: opts.host, port: opts.port });
    const c = new TextConn(conn);
    const greeting = await c.readLine();
    if (!greeting.startsWith("* OK")) {
      c.close();
      throw new Error(`imap: unexpected greeting: ${greeting.slice(0, 80)}`);
    }
    return new ImapSession(c);
  }

  /** Quote a string per the IMAP grammar. */
  static quote(s: string): string {
    return `"${s.replace(/([\\"])/g, "\\$1")}"`;
  }

  async command(cmd: string): Promise<ImapResponse> {
    const tag = `A${++this.#tag}`;
    await this.#c.write(`${tag} ${cmd}${CRLF}`);
    const untagged: { line: string; literal?: Uint8Array }[] = [];
    for (;;) {
      const line = await this.#c.readLine();
      if (line.startsWith(`${tag} `)) {
        const rest = line.slice(tag.length + 1);
        return { ok: rest.startsWith("OK"), text: rest, untagged };
      }
      if (line.startsWith("* ")) {
        // A line ending in {n} announces a literal of n bytes, followed by
        // the rest of the logical line (for FETCH, the closing paren).
        const m = line.match(/\{(\d+)\}$/);
        if (m) {
          const literal = await this.#c.readBytes(Number(m[1]));
          await this.#c.readLine(); // remainder of the FETCH response line
          untagged.push({ line, literal });
        } else {
          untagged.push({ line });
        }
      }
      // Continuation requests (`+ `) don't occur for this command subset.
    }
  }

  async close(): Promise<void> {
    try {
      await this.command("LOGOUT");
    } catch {
      // the server may have hung up already
    }
    this.#c.close();
  }
}

async function smtpExpect(c: TextConn, code: string, sent: string): Promise<void> {
  let line: string;
  do {
    line = await c.readLine();
  } while (/^\d{3}-/.test(line)); // skip multi-line reply continuations
  if (!line.startsWith(code)) {
    throw new Error(`smtp: ${sent} failed: ${line.slice(0, 120)}`);
  }
}

function encodeSubject(subject: string): string {
  if (!/[^\x20-\x7e]/.test(subject)) return subject;
  const b64 = btoa(String.fromCharCode(...new TextEncoder().encode(subject)));
  return `=?utf-8?B?${b64}?=`;
}

/** What {@linkcode smtpSend} needs to deliver one reply. */
export interface SmtpSendOptions {
  host: string;
  port: number;
  /** Implicit TLS (port 465). Plain TCP exists for tests only. */
  tls?: boolean;
  username: string;
  password: string;
  from: string;
  to: string;
  subject: string;
  text: string;
  inReplyTo?: string;
  references?: string;
}

/** Send one message over SMTP (implicit TLS, AUTH PLAIN). Exported for tests. */
export async function smtpSend(opts: SmtpSendOptions): Promise<void> {
  const conn = opts.tls === false
    ? await Deno.connect({ hostname: opts.host, port: opts.port })
    : await Deno.connectTls({ hostname: opts.host, port: opts.port });
  const c = new TextConn(conn);
  try {
    await smtpExpect(c, "220", "greeting");
    const step = async (cmd: string, code: string) => {
      await c.write(cmd + CRLF);
      await smtpExpect(c, code, cmd.split(" ")[0]);
    };
    await step("EHLO looped-agent", "250");
    const plain = btoa(
      String.fromCharCode(...new TextEncoder().encode(`\0${opts.username}\0${opts.password}`)),
    );
    await step(`AUTH PLAIN ${plain}`, "235");
    await step(`MAIL FROM:<${bareAddress(opts.from)}>`, "250");
    await step(`RCPT TO:<${bareAddress(opts.to)}>`, "250");
    await step("DATA", "354");
    const headers = [
      `From: ${opts.from}`,
      `To: ${opts.to}`,
      `Subject: ${encodeSubject(opts.subject)}`,
      `Date: ${new Date().toUTCString()}`,
      `Message-ID: <${crypto.randomUUID()}@looped-agent>`,
      ...(opts.inReplyTo ? [`In-Reply-To: ${opts.inReplyTo}`] : []),
      ...(opts.references ? [`References: ${opts.references}`] : []),
      "MIME-Version: 1.0",
      "Content-Type: text/plain; charset=utf-8",
      "Content-Transfer-Encoding: 8bit",
    ];
    const body = opts.text.replace(/\r?\n/g, CRLF).replace(/^\./gm, ".."); // dot-stuffing
    await c.write(headers.join(CRLF) + CRLF + CRLF + body + CRLF + "." + CRLF);
    await smtpExpect(c, "250", "DATA body");
    await c.write("QUIT" + CRLF);
  } finally {
    c.close();
  }
}

/** Options for {@linkcode ImapEmailTrigger}. */
export interface ImapEmailTriggerOptions {
  /** IMAP server host. */
  host: string;
  /** IMAP port; 993 (implicit TLS) in production. */
  port: number;
  /** Mailbox login, also the address replies are sent from. */
  username: string;
  /** Mailbox password (already resolved from password_env). */
  password: string;
  /** SMTP server for replies. */
  smtpHost: string;
  /** SMTP port; 465 (implicit TLS) in production. */
  smtpPort: number;
  /** Mailbox folder to watch. */
  folder: string;
  /** Seconds between polls. */
  pollSeconds: number;
  /** Senders the agent handles: exact addresses, `*@domain`, or `*`. */
  fromAddresses: string[];
  /** Suppress the reply when the agent answers with the NO_REPLY sentinel (or nothing). */
  allowSilence?: boolean;
  /** Caps on the images an attachment may carry into the context. */
  media: MediaLimits;
  /** Tests only: plain TCP instead of TLS. */
  tls?: boolean;
  /** Tests only: plain TCP for SMTP. */
  smtpTls?: boolean;
}

/**
 * Polls an IMAP mailbox for unseen messages, wakes the agent on the ones that
 * pass the filters and replies over SMTP in the same thread. The unseen flag
 * is the cursor; each handled or dropped message is flagged \Seen.
 */
export class ImapEmailTrigger implements Trigger {
  /** Trigger name, used as the event's `trigger` field. */
  readonly name = "email";
  #opts: ImapEmailTriggerOptions;
  #stopped = false;
  #backoffMs = 1_000;
  #wake?: () => void;

  /** Create the trigger; nothing connects until {@linkcode start}. */
  constructor(opts: ImapEmailTriggerOptions) {
    this.#opts = opts;
  }

  async #connect(): Promise<ImapSession> {
    const { host, port, username, password, folder } = this.#opts;
    const s = await ImapSession.connect({ host, port, tls: this.#opts.tls ?? true });
    const login = await s.command(
      `LOGIN ${ImapSession.quote(username)} ${ImapSession.quote(password)}`,
    );
    if (!login.ok) {
      await s.close();
      throw new Error(`imap: LOGIN failed for ${username} — check the credentials`);
    }
    const select = await s.command(`SELECT ${ImapSession.quote(folder)}`);
    if (!select.ok) {
      await s.close();
      throw new Error(`imap: SELECT ${folder} failed — does the folder exist?`);
    }
    return s;
  }

  /** Verify the credentials and folder, then start the poll loop. */
  async start(emit: (event: AgentEvent) => Promise<RunResult>): Promise<void> {
    // A bad password or folder fails the boot here, ahead of the first message.
    const probe = await this.#connect();
    await probe.close();
    logInfo(
      `email trigger (imap) watching ${this.#opts.folder} of ${this.#opts.username} on ${this.#opts.host}`,
    );
    this.#loop(emit); // poll loop runs for the service's lifetime
  }

  async #loop(emit: (event: AgentEvent) => Promise<RunResult>): Promise<void> {
    while (!this.#stopped) {
      try {
        await this.#pollOnce(emit);
        this.#backoffMs = 1_000;
      } catch (err) {
        if (this.#stopped) return;
        const delay = this.#backoffMs;
        this.#backoffMs = Math.min(delay * 2, 60_000);
        logInfo(`email (imap): poll error (${(err as Error).message}), retrying in ${delay}ms`);
        await this.#sleep(delay);
        continue;
      }
      await this.#sleep(this.#opts.pollSeconds * 1_000);
    }
  }

  #sleep(ms: number): Promise<void> {
    return new Promise((resolve) => {
      const timer = setTimeout(resolve, ms);
      this.#wake = () => {
        clearTimeout(timer);
        resolve();
      };
    });
  }

  async #pollOnce(emit: (event: AgentEvent) => Promise<RunResult>): Promise<void> {
    const s = await this.#connect();
    try {
      const search = await s.command("UID SEARCH UNSEEN");
      if (!search.ok) throw new Error("imap: UID SEARCH failed");
      const uids = search.untagged
        .filter((u) => u.line.toUpperCase().startsWith("* SEARCH"))
        .flatMap((u) => u.line.split(/\s+/).slice(2))
        .filter((n) => /^\d+$/.test(n));

      for (const uid of uids) {
        if (this.#stopped) return;
        const markSeen = () => s.command(`UID STORE ${uid} +FLAGS (\\Seen)`);

        const fetch = await s.command(`UID FETCH ${uid} (BODY.PEEK[])`);
        const raw = fetch.untagged.find((u) => u.literal)?.literal;
        if (!fetch.ok || !raw) {
          await markSeen(); // unfetchable message; don't refetch it forever
          continue;
        }
        const mail = parseMime(raw);

        const own = bareAddress(mail.from) === this.#opts.username.toLowerCase();
        if (
          own || !addressAllowed(mail.from, this.#opts.fromAddresses) ||
          isAutoGenerated(mail.headers)
        ) {
          if (!own && !isAutoGenerated(mail.headers)) {
            logInfo(`email (imap): dropped message from ${mail.from} (not in from_addresses)`);
          }
          await markSeen();
          continue;
        }

        const received: ReceivedEmail = {
          from: mail.from,
          to: mail.to,
          reply_to: mail.headers["reply-to"] ? [mail.headers["reply-to"]] : [],
          subject: mail.subject,
          created_at: mail.date,
          text: mail.text,
          html: mail.html,
          headers: mail.headers,
          message_id: mail.messageId,
          // The FETCH already carried the bytes; there is nothing left to go get.
          attachments: mail.attachments.map((a) => ({
            filename: a.filename,
            mediaType: a.contentType,
            size: a.size,
            fetch: () => Promise.resolve(a.bytes),
          })),
        };
        const { input, images } = await renderEmailInput(received, this.#opts.media);
        const result = await emit({
          id: mail.messageId ?? crypto.randomUUID(),
          trigger: this.name,
          input,
          images,
          conversationKey: threadKey(received),
        });
        await this.#reply(received, result);
        await markSeen(); // after the run: the mailbox is the cursor
      }
    } finally {
      await s.close();
    }
  }

  async #reply(email: ReceivedEmail, result: RunResult): Promise<void> {
    const reply = (result.reply ?? "").trim();
    if (this.#opts.allowSilence && (reply === NO_REPLY || reply === "")) return;

    const subject = /^re:/i.test(email.subject ?? "")
      ? email.subject!
      : `Re: ${email.subject ?? "(no subject)"}`;
    const references = email.message_id
      ? [email.headers?.["references"], email.message_id].filter(Boolean).join(" ")
      : undefined;
    try {
      await smtpSend({
        host: this.#opts.smtpHost,
        port: this.#opts.smtpPort,
        tls: this.#opts.smtpTls,
        username: this.#opts.username,
        password: this.#opts.password,
        from: this.#opts.username,
        to: email.reply_to?.[0] || email.from,
        subject,
        text: reply || `(${result.status})`,
        inReplyTo: email.message_id,
        references,
      });
    } catch (err) {
      logError(`email (imap): reply failed: ${(err as Error).message}`);
    }
  }

  /** Stop the poll loop; the current cycle finishes its message first. */
  stop(): Promise<void> {
    this.#stopped = true;
    this.#wake?.();
    return Promise.resolve();
  }
}
