/**
 * Event sources that wake a Looped AF agent - Discord, Slack, Telegram,
 * email, GitHub, webhook and cron - plus {@linkcode triggersFromConfig}
 * to build them from an agent config.
 *
 * @module
 */

import {
  type AgentConfig,
  commandSpecs,
  DEFAULT_VOICE_API_KEY_ENV,
  type Trigger,
} from "@looped/core";
import { DiscordVoiceSession } from "./discord_voice.ts";
import { WebhookTrigger } from "./webhook.ts";
import { CronTrigger } from "./cron.ts";
import { DiscordTrigger } from "./discord.ts";
import { EmailTrigger } from "./email.ts";
import { GithubTrigger } from "./github.ts";
import { ImapEmailTrigger } from "./email_imap.ts";
import { GmailEmailTrigger } from "./email_gmail.ts";
import { OutlookEmailTrigger } from "./email_outlook.ts";
import { SlackTrigger } from "./slack.ts";
import { TelegramTrigger } from "./telegram.ts";
import { TtyTrigger } from "./tty.ts";
import { voiceFromConfig } from "./voice.ts";

export type {
  AgentConfig,
  AgentEvent,
  CommandConfig,
  CommandSpec,
  CronTriggerConfig,
  DiscordTriggerConfig,
  EmailTriggerConfig,
  GithubTriggerConfig,
  GmailEmailTriggerConfig,
  ImapEmailTriggerConfig,
  LimitsConfig,
  LiveVoiceConfig,
  McpServerConfig,
  MemoryConfig,
  Message,
  ModelConfig,
  OutlookEmailTriggerConfig,
  Permissions,
  ResendEmailTriggerConfig,
  RunResult,
  RunStatus,
  SlackTriggerConfig,
  TelegramTriggerConfig,
  ToolCall,
  Trigger,
  TriggerConfig,
  TtyTriggerConfig,
  Usage,
  VoiceConfig,
  VoiceSttConfig,
  VoiceTtsConfig,
  WebhookTriggerConfig,
} from "@looped/core";
export { NO_REPLY } from "./text.ts";
export { CronTrigger, type CronTriggerOptions } from "./cron.ts";
export { WebhookTrigger, type WebhookTriggerOptions } from "./webhook.ts";
export {
  type TtyClientFrame,
  type TtyServerFrame,
  TtyTrigger,
  type TtyTriggerOptions,
} from "./tty.ts";
export {
  addressAllowed,
  EmailTrigger,
  type EmailTriggerOptions,
  isAutoGenerated,
  type ReceivedEmail,
  renderEmail,
  renderEmailInput,
  type ResendInboundData,
  resendToReceived,
  type SvixVerifyOptions,
  threadKey,
  verifySvixSignature,
} from "./email.ts";
export {
  eventAllowed,
  githubConversationKey,
  type GithubPayload,
  GithubTrigger,
  type GithubTriggerOptions,
  type GithubVerifyOptions,
  renderGithubEvent,
  repoAllowed,
  verifyGithubSignature,
} from "./github.ts";
export {
  ImapEmailTrigger,
  type ImapEmailTriggerOptions,
  smtpSend,
  type SmtpSendOptions,
} from "./email_imap.ts";
export { GmailEmailTrigger, type GmailEmailTriggerOptions } from "./email_gmail.ts";
export { OutlookEmailTrigger, type OutlookEmailTriggerOptions } from "./email_outlook.ts";
export { decodeWords, type ParsedAttachment, type ParsedMail, parseMime } from "./mime.ts";
export {
  type DiscordAttachment,
  discordAttachments,
  type DiscordFilterOptions,
  type DiscordInteraction,
  DiscordTrigger,
  type DiscordTriggerOptions,
  fetchApplicationId,
  INVITE_PERMISSIONS,
  inviteUrl,
} from "./discord.ts";
export {
  slackAttachments,
  type SlackFile,
  type SlackFilterOptions,
  type SlackSlashCommand,
  SlackTrigger,
  type SlackTriggerOptions,
  type SlackVerifyOptions,
  verifySlackSignature,
} from "./slack.ts";
export {
  stripCommandMention,
  type TelegramFilterOptions,
  TelegramTrigger,
  type TelegramTriggerOptions,
} from "./telegram.ts";
export {
  oggOpusDurationSecs,
  placeholderWaveform,
  SPEAK_MAX_CHARS,
  type VoiceClip,
  type VoiceEngines,
  voiceFromConfig,
} from "./voice.ts";
export {
  DiscordVoiceSession,
  type DiscordVoiceSessionOptions,
  type VoiceServerInfo,
} from "./discord_voice.ts";
export { DELEGATE_TOOL, REALTIME_SAMPLE_RATE, RealtimeSession } from "./realtime.ts";
export type { RealtimeSessionOptions } from "./realtime.ts";

/**
 * Instantiate the triggers a config declares.
 * Tokens resolve from *_env here — startup, not first request.
 */
export function triggersFromConfig(
  config: AgentConfig,
  getEnv: (name: string) => string | undefined = Deno.env.get,
): Trigger[] {
  const triggers: Trigger[] = [];
  // Built-ins plus config-defined commands, registered natively on the chat
  // platforms so clients offer a picker with descriptions.
  const commands = commandSpecs(config.commands);
  // What an inbound image may cost, from the same limits: block as the other
  // dead-man's switches — a trigger never invents its own caps.
  const media = {
    maxImageBytes: config.limits.max_image_bytes,
    maxImagesPerMessage: config.limits.max_images_per_message,
  };
  // One set of voice engines shared by every voice-capable trigger; API keys
  // resolve here — startup, not first voice note.
  const voice = config.voice ? voiceFromConfig(config.voice, getEnv) : undefined;
  const live = config.voice?.live;
  // The live session's key resolves at startup too, so a misconfigured agent
  // fails before it joins a channel and sits there mute.
  const liveApiKey = live
    ? getEnv(live.api_key_env ?? DEFAULT_VOICE_API_KEY_ENV[live.provider])
    : undefined;
  if (live && !liveApiKey) {
    throw new Error(
      `voice.live: API key env var ${
        live.api_key_env ?? DEFAULT_VOICE_API_KEY_ENV[live.provider]
      } is not set`,
    );
  }
  for (const t of config.triggers ?? []) {
    switch (t.type) {
      case "webhook": {
        const token = getEnv(t.token_env);
        if (!token) {
          throw new Error(
            `webhook trigger: token env var ${t.token_env} is not set (required for bearer auth)`,
          );
        }
        triggers.push(new WebhookTrigger({ path: t.path, port: t.port, token }));
        break;
      }
      case "tty": {
        const token = getEnv(t.token_env);
        if (!token) {
          throw new Error(
            `tty trigger: token env var ${t.token_env} is not set (required for bearer auth)`,
          );
        }
        triggers.push(
          new TtyTrigger({ path: t.path, port: t.port, token, handle: config.handle }),
        );
        break;
      }
      case "cron":
        triggers.push(new CronTrigger({ schedule: t.schedule, prompt: t.prompt }));
        break;
      case "github": {
        const secret = getEnv(t.secret_env);
        if (!secret) {
          throw new Error(
            `github trigger: webhook secret env var ${t.secret_env} is not set (every delivery's signature is verified)`,
          );
        }
        triggers.push(
          new GithubTrigger({
            path: t.path,
            port: t.port,
            secret,
            events: t.events,
            repos: t.repos,
          }),
        );
        break;
      }
      case "email": {
        switch (t.transport) {
          case "resend": {
            const signingSecret = getEnv(t.signing_secret_env);
            if (!signingSecret) {
              throw new Error(
                `email trigger: signing secret env var ${t.signing_secret_env} is not set (Resend signs every webhook)`,
              );
            }
            const apiKey = getEnv(t.api_key_env);
            if (!apiKey) {
              throw new Error(
                `email trigger: API key env var ${t.api_key_env} is not set (needed to fetch message bodies and send replies)`,
              );
            }
            triggers.push(
              new EmailTrigger({
                path: t.path,
                port: t.port,
                signingSecret,
                apiKey,
                fromAddresses: t.from_addresses,
                allowSilence: t.allow_silence,
                media,
              }),
            );
            break;
          }
          case "imap": {
            const password = getEnv(t.password_env);
            if (!password) {
              throw new Error(
                `email trigger: password env var ${t.password_env} is not set (the IMAP login needs it)`,
              );
            }
            triggers.push(
              new ImapEmailTrigger({
                host: t.host,
                port: t.port,
                username: t.username,
                password,
                smtpHost: t.smtp_host,
                smtpPort: t.smtp_port,
                folder: t.folder,
                pollSeconds: t.poll_seconds,
                fromAddresses: t.from_addresses,
                allowSilence: t.allow_silence,
                media,
              }),
            );
            break;
          }
          case "gmail": {
            const clientSecret = getEnv(t.client_secret_env);
            if (!clientSecret) {
              throw new Error(
                `email trigger: client secret env var ${t.client_secret_env} is not set (the Gmail token refresh needs it)`,
              );
            }
            const refreshToken = getEnv(t.refresh_token_env);
            if (!refreshToken) {
              throw new Error(
                `email trigger: refresh token env var ${t.refresh_token_env} is not set (run the one-time consent flow — docs/email.mdx)`,
              );
            }
            triggers.push(
              new GmailEmailTrigger({
                clientId: t.client_id,
                clientSecret,
                refreshToken,
                label: t.label,
                pollSeconds: t.poll_seconds,
                fromAddresses: t.from_addresses,
                allowSilence: t.allow_silence,
                media,
              }),
            );
            break;
          }
          case "outlook": {
            const refreshToken = getEnv(t.refresh_token_env);
            if (!refreshToken) {
              throw new Error(
                `email trigger: refresh token env var ${t.refresh_token_env} is not set (run the one-time device-code flow — docs/email.mdx)`,
              );
            }
            let clientSecret: string | undefined;
            if (t.client_secret_env) {
              clientSecret = getEnv(t.client_secret_env);
              if (!clientSecret) {
                throw new Error(
                  `email trigger: client secret env var ${t.client_secret_env} is named in config but not set`,
                );
              }
            }
            triggers.push(
              new OutlookEmailTrigger({
                clientId: t.client_id,
                clientSecret,
                refreshToken,
                tenant: t.tenant,
                folder: t.folder,
                pollSeconds: t.poll_seconds,
                fromAddresses: t.from_addresses,
                allowSilence: t.allow_silence,
                media,
              }),
            );
            break;
          }
        }
        break;
      }
      case "discord": {
        const token = getEnv(t.token_env);
        if (!token) {
          throw new Error(
            `discord trigger: bot token env var ${t.token_env} is not set`,
          );
        }
        triggers.push(
          new DiscordTrigger({
            token,
            channels: t.channels,
            requireMention: t.require_mention,
            fromUsers: t.from_users,
            replyChannel: t.reply_channel,
            allowSilence: t.allow_silence,
            showTyping: t.show_typing,
            commands,
            media,
            voice,
            voiceChannels: t.voice_channels,
            liveVoice: live && t.voice_channels?.length
              ? (delegate) =>
                new DiscordVoiceSession({
                  config: live,
                  apiKey: liveApiKey!,
                  // The voice model speaks as this agent, so it gets the same
                  // job description the text loop runs on.
                  instructions: config.purpose,
                  delegate,
                })
              : undefined,
          }),
        );
        break;
      }
      case "slack": {
        const token = getEnv(t.token_env);
        if (!token) {
          throw new Error(`slack trigger: bot token env var ${t.token_env} is not set`);
        }
        // Each transport resolves only its own secret — startup, not first event.
        let appToken: string | undefined;
        let signingSecret: string | undefined;
        if (t.transport === "events_api") {
          signingSecret = getEnv(t.signing_secret_env);
          if (!signingSecret) {
            throw new Error(
              `slack trigger: signing secret env var ${t.signing_secret_env} is not set (every Events API delivery is verified)`,
            );
          }
        } else {
          appToken = getEnv(t.app_token_env);
          if (!appToken) {
            throw new Error(
              `slack trigger: app-level token env var ${t.app_token_env} is not set (Socket Mode needs it)`,
            );
          }
        }
        triggers.push(
          new SlackTrigger({
            token,
            appToken,
            transport: t.transport,
            port: t.port,
            path: t.path,
            signingSecret,
            channels: t.channels,
            requireMention: t.require_mention,
            fromUsers: t.from_users,
            replyChannel: t.reply_channel,
            allowSilence: t.allow_silence,
            media,
          }),
        );
        break;
      }
      case "telegram": {
        const token = getEnv(t.token_env);
        if (!token) {
          throw new Error(`telegram trigger: bot token env var ${t.token_env} is not set`);
        }
        triggers.push(
          new TelegramTrigger({
            token,
            transport: t.transport,
            port: t.port,
            path: t.path,
            publicUrl: t.public_url,
            chats: t.chats,
            requireMention: t.require_mention,
            fromUsers: t.from_users,
            replyChat: t.reply_chat,
            allowSilence: t.allow_silence,
            commands,
            media,
            voice,
          }),
        );
        break;
      }
    }
  }
  return triggers;
}
