/**
 * Event sources that wake a Looped AF agent - Discord, Slack, Telegram,
 * webhook and cron - plus {@linkcode triggersFromConfig} to build them
 * from an agent config.
 *
 * @module
 */

import { type AgentConfig, commandSpecs, type Trigger } from "@looped/core";
import { WebhookTrigger } from "./webhook.ts";
import { CronTrigger } from "./cron.ts";
import { DiscordTrigger } from "./discord.ts";
import { EmailTrigger } from "./email.ts";
import { ImapEmailTrigger } from "./email_imap.ts";
import { GmailEmailTrigger } from "./email_gmail.ts";
import { OutlookEmailTrigger } from "./email_outlook.ts";
import { SlackTrigger } from "./slack.ts";
import { TelegramTrigger } from "./telegram.ts";

export type {
  AgentConfig,
  AgentEvent,
  CommandConfig,
  CommandSpec,
  CronTriggerConfig,
  DiscordTriggerConfig,
  EmailTriggerConfig,
  GmailEmailTriggerConfig,
  ImapEmailTriggerConfig,
  LimitsConfig,
  McpServerConfig,
  MemoryConfig,
  Message,
  ModelConfig,
  OutlookEmailTriggerConfig,
  Permissions,
  ResendEmailTriggerConfig,
  RunResult,
  RunStatus,
  SlackTriggerConfig,
  TelegramTriggerConfig,
  ToolCall,
  Trigger,
  TriggerConfig,
  Usage,
  WebhookTriggerConfig,
} from "@looped/core";
export { NO_REPLY } from "./text.ts";
export { CronTrigger, type CronTriggerOptions } from "./cron.ts";
export { WebhookTrigger, type WebhookTriggerOptions } from "./webhook.ts";
export {
  addressAllowed,
  EmailTrigger,
  type EmailTriggerOptions,
  isAutoGenerated,
  type ReceivedEmail,
  renderEmail,
  type ResendInboundData,
  type SvixVerifyOptions,
  threadKey,
  verifySvixSignature,
} from "./email.ts";
export {
  ImapEmailTrigger,
  type ImapEmailTriggerOptions,
  smtpSend,
  type SmtpSendOptions,
} from "./email_imap.ts";
export { GmailEmailTrigger, type GmailEmailTriggerOptions } from "./email_gmail.ts";
export { OutlookEmailTrigger, type OutlookEmailTriggerOptions } from "./email_outlook.ts";
export { decodeWords, type ParsedMail, parseMime } from "./mime.ts";
export {
  type DiscordFilterOptions,
  type DiscordInteraction,
  DiscordTrigger,
  type DiscordTriggerOptions,
  fetchApplicationId,
  INVITE_PERMISSIONS,
  inviteUrl,
} from "./discord.ts";
export {
  type SlackFilterOptions,
  type SlackSlashCommand,
  SlackTrigger,
  type SlackTriggerOptions,
} from "./slack.ts";
export {
  stripCommandMention,
  type TelegramFilterOptions,
  TelegramTrigger,
  type TelegramTriggerOptions,
} from "./telegram.ts";

/**
 * Instantiate the triggers a config declares.
 * Tokens resolve from *_env here — startup, not first request.
 */
export function triggersFromConfig(
  config: AgentConfig,
  getEnv: (name: string) => string | undefined = Deno.env.get,
): Trigger[] {
  const triggers: Trigger[] = [];
  // Built-ins plus config-defined commands, registered natively on the chat
  // platforms so clients offer a picker with descriptions.
  const commands = commandSpecs(config.commands);
  for (const t of config.triggers ?? []) {
    switch (t.type) {
      case "webhook": {
        const token = getEnv(t.token_env);
        if (!token) {
          throw new Error(
            `webhook trigger: token env var ${t.token_env} is not set (required for bearer auth)`,
          );
        }
        triggers.push(new WebhookTrigger({ path: t.path, port: t.port, token }));
        break;
      }
      case "cron":
        triggers.push(new CronTrigger({ schedule: t.schedule, prompt: t.prompt }));
        break;
      case "email": {
        switch (t.transport) {
          case "resend": {
            const signingSecret = getEnv(t.signing_secret_env);
            if (!signingSecret) {
              throw new Error(
                `email trigger: signing secret env var ${t.signing_secret_env} is not set (Resend signs every webhook)`,
              );
            }
            const apiKey = getEnv(t.api_key_env);
            if (!apiKey) {
              throw new Error(
                `email trigger: API key env var ${t.api_key_env} is not set (needed to fetch message bodies and send replies)`,
              );
            }
            triggers.push(
              new EmailTrigger({
                path: t.path,
                port: t.port,
                signingSecret,
                apiKey,
                fromAddresses: t.from_addresses,
                allowSilence: t.allow_silence,
              }),
            );
            break;
          }
          case "imap": {
            const password = getEnv(t.password_env);
            if (!password) {
              throw new Error(
                `email trigger: password env var ${t.password_env} is not set (the IMAP login needs it)`,
              );
            }
            triggers.push(
              new ImapEmailTrigger({
                host: t.host,
                port: t.port,
                username: t.username,
                password,
                smtpHost: t.smtp_host,
                smtpPort: t.smtp_port,
                folder: t.folder,
                pollSeconds: t.poll_seconds,
                fromAddresses: t.from_addresses,
                allowSilence: t.allow_silence,
              }),
            );
            break;
          }
          case "gmail": {
            const clientSecret = getEnv(t.client_secret_env);
            if (!clientSecret) {
              throw new Error(
                `email trigger: client secret env var ${t.client_secret_env} is not set (the Gmail token refresh needs it)`,
              );
            }
            const refreshToken = getEnv(t.refresh_token_env);
            if (!refreshToken) {
              throw new Error(
                `email trigger: refresh token env var ${t.refresh_token_env} is not set (run the one-time consent flow — docs/email.mdx)`,
              );
            }
            triggers.push(
              new GmailEmailTrigger({
                clientId: t.client_id,
                clientSecret,
                refreshToken,
                label: t.label,
                pollSeconds: t.poll_seconds,
                fromAddresses: t.from_addresses,
                allowSilence: t.allow_silence,
              }),
            );
            break;
          }
          case "outlook": {
            const refreshToken = getEnv(t.refresh_token_env);
            if (!refreshToken) {
              throw new Error(
                `email trigger: refresh token env var ${t.refresh_token_env} is not set (run the one-time device-code flow — docs/email.mdx)`,
              );
            }
            let clientSecret: string | undefined;
            if (t.client_secret_env) {
              clientSecret = getEnv(t.client_secret_env);
              if (!clientSecret) {
                throw new Error(
                  `email trigger: client secret env var ${t.client_secret_env} is named in config but not set`,
                );
              }
            }
            triggers.push(
              new OutlookEmailTrigger({
                clientId: t.client_id,
                clientSecret,
                refreshToken,
                tenant: t.tenant,
                folder: t.folder,
                pollSeconds: t.poll_seconds,
                fromAddresses: t.from_addresses,
                allowSilence: t.allow_silence,
              }),
            );
            break;
          }
        }
        break;
      }
      case "discord": {
        const token = getEnv(t.token_env);
        if (!token) {
          throw new Error(
            `discord trigger: bot token env var ${t.token_env} is not set`,
          );
        }
        triggers.push(
          new DiscordTrigger({
            token,
            channels: t.channels,
            requireMention: t.require_mention,
            fromUsers: t.from_users,
            replyChannel: t.reply_channel,
            allowSilence: t.allow_silence,
            showTyping: t.show_typing,
            commands,
          }),
        );
        break;
      }
      case "slack": {
        const token = getEnv(t.token_env);
        if (!token) {
          throw new Error(`slack trigger: bot token env var ${t.token_env} is not set`);
        }
        const appToken = getEnv(t.app_token_env);
        if (!appToken) {
          throw new Error(
            `slack trigger: app-level token env var ${t.app_token_env} is not set (Socket Mode needs it)`,
          );
        }
        triggers.push(
          new SlackTrigger({
            token,
            appToken,
            channels: t.channels,
            requireMention: t.require_mention,
            fromUsers: t.from_users,
            replyChannel: t.reply_channel,
            allowSilence: t.allow_silence,
          }),
        );
        break;
      }
      case "telegram": {
        const token = getEnv(t.token_env);
        if (!token) {
          throw new Error(`telegram trigger: bot token env var ${t.token_env} is not set`);
        }
        triggers.push(
          new TelegramTrigger({
            token,
            chats: t.chats,
            requireMention: t.require_mention,
            fromUsers: t.from_users,
            replyChat: t.reply_chat,
            allowSilence: t.allow_silence,
            commands,
          }),
        );
        break;
      }
    }
  }
  return triggers;
}
